language: swift
osx_image: xcode12.5.1
branches:
  only:
    - main

before_install:
  - gem install fastlane  -N --no-document
install: true
script:
  - fastlane scan --scheme Default --device "iPhone 11 Pro"		
